-- =====================================================================
--  LokaSetu v4.3 migration
--
--  Run AFTER supabase/schema.sql. Paste the whole file into
--  Supabase -> SQL Editor -> New query -> Run.
--
--  Idempotent: every statement is IF NOT EXISTS or DROP-then-CREATE.
--  It adds columns and one table. It alters nothing that already holds
--  data and drops nothing.
-- =====================================================================


-- ---------------------------------------------------------------------
--  1. Address, on the profile
--
--  City, area and society are LOCALITY level. They are safe to show
--  before a booking is accepted, which is exactly what the spec asks
--  for: "show only area/locality". They live on the world-readable
--  profiles table on purpose.
--
--  The exact address and the phone number do NOT live here. See §3.
-- ---------------------------------------------------------------------
alter table public.profiles add column if not exists city                TEXT;
alter table public.profiles add column if not exists area                TEXT;
alter table public.profiles add column if not exists society             TEXT;
alter table public.profiles add column if not exists preferred_language  TEXT not null default 'en';

alter table public.profiles drop constraint if exists profiles_language_check;
alter table public.profiles add  constraint profiles_language_check
  check (preferred_language in ('en','hi','bn','ta','te','kn','ml','mr','gu','pa'));

create index if not exists profiles_city_area_idx on public.profiles (city, area);


-- ---------------------------------------------------------------------
--  2. Who may post what
--
--  Residents create job requests. Workers post availability updates and
--  answer offers. Neither can do the other's job, and this is the layer
--  that makes it true: the front end greys the control out, and the
--  database refuses regardless of what the front end did.
-- ---------------------------------------------------------------------
create or replace function public.guard_post_role()
returns trigger
language plpgsql
security definer
set search_path = public
as $fn$
declare
  author_role text;
begin
  select role into author_role from public.profiles where id = new.user_id;

  if author_role is null then
    raise exception 'no profile for this user' using errcode = '42501';
  end if;

  if new.post_type = 'job' and author_role <> 'employer' then
    raise exception 'only a resident account can post a job request'
      using errcode = '42501';
  end if;

  if new.post_type = 'update' and author_role <> 'worker' then
    raise exception 'only a worker account can post an availability update'
      using errcode = '42501';
  end if;

  return new;
end;
$fn$;

drop trigger if exists posts_guard_role on public.posts;
create trigger posts_guard_role
  before insert or update of post_type, user_id on public.posts
  for each row execute function public.guard_post_role();


-- ---------------------------------------------------------------------
--  3. Private details
--
--  YOU ASKED FOR `phone text` ON `profiles`. It is not there, and this
--  is why: `profiles` is world-readable — it has to be, it is the
--  directory of who does what work. Row Level Security is per ROW, not
--  per COLUMN, so a phone column on that table is readable by anyone
--  holding the anon key no matter what the UI chooses to render. The
--  rule "public feeds never expose phone numbers" would be a UI
--  convention rather than a fact.
--
--  So the phone and the exact address live here instead, with a policy
--  that enforces the rule you actually asked for: readable by the owner,
--  and by the other party once an offer between the two of you has been
--  accepted. Nobody else, ever, at any layer.
--
--    post_id IS NULL  -> this person's own contact details (phone)
--    post_id IS SET   -> the exact address for one specific job
-- ---------------------------------------------------------------------
create table if not exists public.private_details (
  id          BIGINT generated by default as identity primary key,
  owner_id    UUID not null references public.profiles(id) on delete cascade,
  post_id     BIGINT references public.posts(id) on delete cascade,
  phone       TEXT,
  flat_number TEXT,
  landmark    TEXT,
  notes       TEXT,
  created_at  TIMESTAMPTZ not null default now(),
  updated_at  TIMESTAMPTZ not null default now()
);

-- One personal row per person, one job row per person per post.
-- Partial indexes, because a plain UNIQUE treats NULLs as distinct and
-- would let somebody accumulate a hundred personal rows.
create unique index if not exists private_details_self_idx
  on public.private_details (owner_id) where post_id is null;

create unique index if not exists private_details_post_idx
  on public.private_details (owner_id, post_id) where post_id is not null;

create index if not exists private_details_owner_idx on public.private_details (owner_id);

drop trigger if exists private_details_touch on public.private_details;
create trigger private_details_touch
  before update on public.private_details
  for each row execute function public.touch_updated_at();

alter table public.private_details enable row level security;

drop policy if exists "private: owner or accepted counterparty" on public.private_details;
drop policy if exists "private: insert own"                      on public.private_details;
drop policy if exists "private: update own"                      on public.private_details;
drop policy if exists "private: delete own"                      on public.private_details;

-- The whole feature, in one policy.
create policy "private: owner or accepted counterparty"
  on public.private_details for select
  to authenticated
  using (
    auth.uid() = owner_id
    or exists (
      select 1
        from public.offers o
       where o.status = 'accepted'
         and (
              (o.employer_id = private_details.owner_id and o.worker_id   = auth.uid())
           or (o.worker_id   = private_details.owner_id and o.employer_id = auth.uid())
         )
         and (private_details.post_id is null or o.post_id = private_details.post_id)
    )
  );

create policy "private: insert own"
  on public.private_details for insert
  to authenticated
  with check (auth.uid() = owner_id);

create policy "private: update own"
  on public.private_details for update
  to authenticated
  using (auth.uid() = owner_id)
  with check (auth.uid() = owner_id);

create policy "private: delete own"
  on public.private_details for delete
  to authenticated
  using (auth.uid() = owner_id);


-- ---------------------------------------------------------------------
--  4. Realtime
--
--  So a revealed phone number appears the moment the offer is accepted,
--  without a refresh.
-- ---------------------------------------------------------------------
do $realtime$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    if not exists (
      select 1 from pg_publication_tables
       where pubname = 'supabase_realtime'
         and schemaname = 'public'
         and tablename = 'private_details'
    ) then
      alter publication supabase_realtime add table public.private_details;
    end if;
    alter table public.private_details replica identity full;
  end if;
end
$realtime$;


-- =====================================================================
--  Verify
--
--    select column_name from information_schema.columns
--     where table_name = 'profiles' and table_schema = 'public'
--     order by 1;
--    -- expect city, area, society, preferred_language among them
--
--    select policyname from pg_policies
--     where tablename = 'private_details';
--    -- expect four
--
--    select tgname from pg_trigger
--     where tgrelid = 'public.posts'::regclass and not tgisinternal;
--    -- expect posts_guard_role
-- =====================================================================
