-- =====================================================================
--  LokaSetu — database schema
--  Paste this whole file into Supabase -> SQL Editor -> New query -> Run.
--
--  SAFE TO RUN ON A DATABASE THAT ALREADY HAS THE FOUR TABLES.
--  Every statement is idempotent: tables use CREATE TABLE IF NOT EXISTS
--  with exactly the DDL you already ran, added columns use ADD COLUMN IF
--  NOT EXISTS, and every policy and trigger is dropped before it is
--  created. Running it twice changes nothing the second time.
--
--  It is also safe to run on an empty project: it creates everything.
-- =====================================================================


-- ---------------------------------------------------------------------
--  0.  Extensions
-- ---------------------------------------------------------------------
create extension if not exists "pgcrypto" with schema extensions;


-- ---------------------------------------------------------------------
--  1.  PROFILES  (unchanged from the schema already running)
-- ---------------------------------------------------------------------
create table if not exists public.profiles (
  id UUID references auth.users on delete cascade primary key,
  updated_at TIMESTAMPTZ default now(),
  username TEXT unique,
  full_name TEXT,
  avatar_url TEXT,
  bio TEXT,
  location TEXT
);

-- ---------------------------------------------------------------------
--  2.  POSTS / UPDATES  (unchanged)
-- ---------------------------------------------------------------------
create table if not exists public.posts (
  id BIGINT generated by default as identity primary key,
  created_at TIMESTAMPTZ default now(),
  user_id UUID references public.profiles(id) on delete cascade not null,
  content TEXT not null,
  media_url TEXT
);

-- ---------------------------------------------------------------------
--  3.  CONNECTIONS  (unchanged)
-- ---------------------------------------------------------------------
create table if not exists public.connections (
  id BIGINT generated by default as identity primary key,
  created_at TIMESTAMPTZ default now(),
  requester_id UUID references public.profiles(id) on delete cascade not null,
  receiver_id UUID references public.profiles(id) on delete cascade not null,
  status TEXT default 'pending' check (status in ('pending', 'accepted', 'rejected', 'blocked')),
  constraint unique_connection unique (requester_id, receiver_id)
);

-- ---------------------------------------------------------------------
--  4.  OFFERS  (unchanged) — Rapido-style price negotiation
-- ---------------------------------------------------------------------
create table if not exists public.offers (
  id BIGINT generated by default as identity primary key,
  created_at TIMESTAMPTZ default now(),
  post_id BIGINT references public.posts(id) on delete cascade,
  employer_id UUID references public.profiles(id) on delete cascade not null,
  worker_id UUID references public.profiles(id) on delete cascade not null,
  offered_price NUMERIC(10, 2) not null,
  status TEXT default 'pending' check (status in ('pending', 'accepted', 'declined', 'countered'))
);


-- =====================================================================
--  5.  ADDITIVE COLUMNS
--
--  The four tables above are yours, untouched. These are the columns the
--  application needs on top of them. Each one is nullable or has a
--  default, so adding them to a table that already holds rows cannot
--  fail and cannot lose data.
--
--  Deliberately NOT added: a phone column. A public profile directory
--  with a phone number in it is a phone number leak waiting to happen.
--  People reach each other through connections and offers instead.
-- =====================================================================

alter table public.profiles add column if not exists role        TEXT not null default 'worker';
alter table public.profiles add column if not exists skills      TEXT[] not null default '{}';
alter table public.profiles add column if not exists hourly_rate NUMERIC(10,2);
alter table public.profiles add column if not exists verified    BOOLEAN not null default false;
alter table public.profiles add column if not exists created_at  TIMESTAMPTZ not null default now();

alter table public.posts add column if not exists title     TEXT;
alter table public.posts add column if not exists category  TEXT;
alter table public.posts add column if not exists budget    NUMERIC(10,2);
alter table public.posts add column if not exists location  TEXT;
alter table public.posts add column if not exists post_type TEXT not null default 'job';
alter table public.posts add column if not exists status    TEXT not null default 'open';

alter table public.offers add column if not exists message    TEXT;
alter table public.offers add column if not exists updated_at TIMESTAMPTZ not null default now();
alter table public.offers add column if not exists round      INTEGER not null default 1;
alter table public.offers add column if not exists last_actor UUID references public.profiles(id) on delete set null;

-- Constraints for the added columns. Dropped first so the file re-runs.
alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles add  constraint profiles_role_check
  check (role in ('worker', 'employer'));

alter table public.posts drop constraint if exists posts_post_type_check;
alter table public.posts add  constraint posts_post_type_check
  check (post_type in ('job', 'update'));

alter table public.posts drop constraint if exists posts_status_check;
alter table public.posts add  constraint posts_status_check
  check (status in ('open', 'assigned', 'completed', 'cancelled'));

alter table public.offers drop constraint if exists offers_price_positive;
alter table public.offers add  constraint offers_price_positive
  check (offered_price > 0 and offered_price <= 10000000);

alter table public.connections drop constraint if exists connections_not_self;
alter table public.connections add  constraint connections_not_self
  check (requester_id <> receiver_id);


-- =====================================================================
--  6.  INDEXES
-- =====================================================================
create index if not exists posts_created_at_idx    on public.posts (created_at desc);
create index if not exists posts_user_id_idx       on public.posts (user_id);
create index if not exists posts_category_idx      on public.posts (category);
create index if not exists posts_type_status_idx   on public.posts (post_type, status);

create index if not exists connections_receiver_idx  on public.connections (receiver_id, status);
create index if not exists connections_requester_idx on public.connections (requester_id, status);

create index if not exists offers_worker_idx   on public.offers (worker_id, status);
create index if not exists offers_employer_idx on public.offers (employer_id, status);
create index if not exists offers_post_idx     on public.offers (post_id);

create index if not exists profiles_role_idx     on public.profiles (role);
create index if not exists profiles_location_idx on public.profiles (location);


-- =====================================================================
--  7.  TRIGGERS
--
--  Rules that must hold no matter what the client sends. Anything
--  enforced only in React is a suggestion; anything enforced here is a
--  rule. These are the rules.
-- =====================================================================

-- 7a. updated_at maintenance -------------------------------------------------
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $fn$
begin
  new.updated_at := now();
  return new;
end;
$fn$;

drop trigger if exists profiles_touch_updated_at on public.profiles;
create trigger profiles_touch_updated_at
  before update on public.profiles
  for each row execute function public.touch_updated_at();

drop trigger if exists offers_touch_updated_at on public.offers;
create trigger offers_touch_updated_at
  before update on public.offers
  for each row execute function public.touch_updated_at();


-- 7b. A role cannot be changed from the front end -----------------------------
--     Chosen once, at sign-up, and immutable after that. The UI has no way
--     around this: the database raises, and PostgREST returns the error.
create or replace function public.freeze_profile_role()
returns trigger
language plpgsql
as $fn$
begin
  if new.role is distinct from old.role then
    raise exception 'role is immutable once set (attempted % -> %)', old.role, new.role
      using errcode = '42501';
  end if;
  if new.id is distinct from old.id then
    raise exception 'profile id is immutable' using errcode = '42501';
  end if;
  return new;
end;
$fn$;

drop trigger if exists profiles_freeze_role on public.profiles;
create trigger profiles_freeze_role
  before update on public.profiles
  for each row execute function public.freeze_profile_role();


-- 7c. An offer's parties never move, and a settled offer stays settled ---------
create or replace function public.guard_offer_update()
returns trigger
language plpgsql
as $fn$
begin
  if new.post_id     is distinct from old.post_id
  or new.employer_id is distinct from old.employer_id
  or new.worker_id   is distinct from old.worker_id then
    raise exception 'an offer cannot be reassigned to a different post or party'
      using errcode = '42501';
  end if;

  if old.status in ('accepted', 'declined')
     and (new.status is distinct from old.status
          or new.offered_price is distinct from old.offered_price) then
    raise exception 'offer % is already %, it cannot be changed', old.id, old.status
      using errcode = '42501';
  end if;

  -- Changing the number IS the counter-offer. Recording who moved last is what
  -- makes the next rule possible.
  if new.offered_price is distinct from old.offered_price then
    if new.status is distinct from 'countered' then
      raise exception 'changing the price makes this a counter-offer; status must be countered'
        using errcode = '42501';
    end if;
    new.round      := old.round + 1;
    new.last_actor := auth.uid();

  -- Nobody accepts their own number. Whoever named the current price has to
  -- wait for the other side to say yes. Without this, one UPDATE could set a
  -- price and accept it in the same breath.
  elsif new.status = 'accepted'
        and old.last_actor is not null
        and auth.uid() = old.last_actor then
    raise exception 'the side that proposed this price cannot also accept it'
      using errcode = '42501';
  end if;

  return new;
end;
$fn$;

drop trigger if exists offers_guard_update on public.offers;
create trigger offers_guard_update
  before update on public.offers
  for each row execute function public.guard_offer_update();


-- 7c-ii. The opening price is always the employer's -------------------------
create or replace function public.stamp_offer_insert()
returns trigger
language plpgsql
as $fn$
begin
  new.last_actor := new.employer_id;
  new.round      := 1;
  new.status     := coalesce(new.status, 'pending');
  return new;
end;
$fn$;

drop trigger if exists offers_stamp_insert on public.offers;
create trigger offers_stamp_insert
  before insert on public.offers
  for each row execute function public.stamp_offer_insert();


-- 7d. Only the receiver of a request may accept or reject it -------------------
create or replace function public.guard_connection_update()
returns trigger
language plpgsql
as $fn$
begin
  if new.requester_id is distinct from old.requester_id
  or new.receiver_id  is distinct from old.receiver_id then
    raise exception 'a connection cannot be reassigned' using errcode = '42501';
  end if;

  if new.status is distinct from old.status
     and new.status in ('accepted', 'rejected')
     and auth.uid() is distinct from old.receiver_id then
    raise exception 'only the person who received the request can answer it'
      using errcode = '42501';
  end if;

  return new;
end;
$fn$;

drop trigger if exists connections_guard_update on public.connections;
create trigger connections_guard_update
  before update on public.connections
  for each row execute function public.guard_connection_update();


-- 7e. Every new auth user gets a profile row, immediately ---------------------
--     Without this, sign-up succeeds and then the app has a user with no
--     profile — the single most common way a Supabase app breaks on day one.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $fn$
declare
  wanted_role text;
  base_name   text;
  candidate   text;
  suffix      int := 0;
begin
  wanted_role := coalesce(new.raw_user_meta_data ->> 'role', 'worker');
  if wanted_role not in ('worker', 'employer') then
    wanted_role := 'worker';
  end if;

  base_name := lower(regexp_replace(
    coalesce(nullif(new.raw_user_meta_data ->> 'username', ''), split_part(new.email, '@', 1)),
    '[^a-zA-Z0-9_]', '', 'g'));
  if base_name is null or base_name = '' then
    base_name := 'member';
  end if;

  candidate := base_name;
  while exists (select 1 from public.profiles p where p.username = candidate) loop
    suffix    := suffix + 1;
    candidate := base_name || suffix::text;
  end loop;

  insert into public.profiles (id, username, full_name, role, location, avatar_url, bio)
  values (
    new.id,
    candidate,
    coalesce(nullif(new.raw_user_meta_data ->> 'full_name', ''), initcap(base_name)),
    wanted_role,
    nullif(new.raw_user_meta_data ->> 'location', ''),
    nullif(new.raw_user_meta_data ->> 'avatar_url', ''),
    nullif(new.raw_user_meta_data ->> 'bio', '')
  )
  on conflict (id) do nothing;

  return new;
end;
$fn$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();


-- =====================================================================
--  8.  ROW LEVEL SECURITY
--
--  On for every table, with policies written against auth.uid(). There
--  is no anonymous write anywhere: you must be signed in, and you can
--  only write rows that are yours.
-- =====================================================================

alter table public.profiles    enable row level security;
alter table public.posts       enable row level security;
alter table public.connections enable row level security;
alter table public.offers      enable row level security;

-- 8a. profiles ---------------------------------------------------------------
drop policy if exists "profiles: readable by anyone"   on public.profiles;
drop policy if exists "profiles: insert own"           on public.profiles;
drop policy if exists "profiles: update own"           on public.profiles;

-- Readable by anyone: this is a public directory of who does what work, and
-- it holds nothing private. There is no phone number, no email, no address —
-- location is a city or neighbourhood name that the person typed themselves.
create policy "profiles: readable by anyone"
  on public.profiles for select
  using (true);

create policy "profiles: insert own"
  on public.profiles for insert
  to authenticated
  with check (auth.uid() = id);

create policy "profiles: update own"
  on public.profiles for update
  to authenticated
  using (auth.uid() = id)
  with check (auth.uid() = id);
-- No delete policy. A profile disappears only when the auth user is deleted,
-- which cascades. Nobody can delete somebody else's identity.

-- 8b. posts ------------------------------------------------------------------
drop policy if exists "posts: readable by anyone" on public.posts;
drop policy if exists "posts: insert own"         on public.posts;
drop policy if exists "posts: update own"         on public.posts;
drop policy if exists "posts: delete own"         on public.posts;

create policy "posts: readable by anyone"
  on public.posts for select
  using (true);

create policy "posts: insert own"
  on public.posts for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "posts: update own"
  on public.posts for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "posts: delete own"
  on public.posts for delete
  to authenticated
  using (auth.uid() = user_id);

-- 8c. connections ------------------------------------------------------------
--     Private to the two people involved. Nobody can enumerate somebody
--     else's network.
drop policy if exists "connections: readable by the two parties" on public.connections;
drop policy if exists "connections: request as self"             on public.connections;
drop policy if exists "connections: answer if involved"          on public.connections;
drop policy if exists "connections: withdraw if involved"        on public.connections;

create policy "connections: readable by the two parties"
  on public.connections for select
  to authenticated
  using (auth.uid() = requester_id or auth.uid() = receiver_id);

create policy "connections: request as self"
  on public.connections for insert
  to authenticated
  with check (auth.uid() = requester_id and requester_id <> receiver_id);

create policy "connections: answer if involved"
  on public.connections for update
  to authenticated
  using (auth.uid() = requester_id or auth.uid() = receiver_id)
  with check (auth.uid() = requester_id or auth.uid() = receiver_id);

create policy "connections: withdraw if involved"
  on public.connections for delete
  to authenticated
  using (auth.uid() = requester_id or auth.uid() = receiver_id);

-- 8d. offers -----------------------------------------------------------------
--     A negotiation is between exactly two people. Nobody else can read the
--     price, not even the rest of the network.
drop policy if exists "offers: readable by the two parties" on public.offers;
drop policy if exists "offers: employer proposes"           on public.offers;
drop policy if exists "offers: either party answers"        on public.offers;
drop policy if exists "offers: employer withdraws"          on public.offers;

create policy "offers: readable by the two parties"
  on public.offers for select
  to authenticated
  using (auth.uid() = employer_id or auth.uid() = worker_id);

create policy "offers: employer proposes"
  on public.offers for insert
  to authenticated
  with check (auth.uid() = employer_id and employer_id <> worker_id);

create policy "offers: either party answers"
  on public.offers for update
  to authenticated
  using (auth.uid() = employer_id or auth.uid() = worker_id)
  with check (auth.uid() = employer_id or auth.uid() = worker_id);

create policy "offers: employer withdraws"
  on public.offers for delete
  to authenticated
  using (auth.uid() = employer_id and status = 'pending');


-- =====================================================================
--  9.  REALTIME
--
--  Adds the tables to Supabase's realtime publication if they are not
--  already in it, and sets replica identity so UPDATE and DELETE events
--  carry the whole row (without this, realtime fires but the payload is
--  missing the columns the UI needs).
-- =====================================================================
do $realtime$
declare
  t text;
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    foreach t in array array['profiles', 'posts', 'connections', 'offers'] loop
      if not exists (
        select 1 from pg_publication_tables
         where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = t
      ) then
        execute format('alter publication supabase_realtime add table public.%I', t);
      end if;
      execute format('alter table public.%I replica identity full', t);
    end loop;
  else
    raise notice 'publication supabase_realtime not found - skipping realtime setup';
  end if;
end
$realtime$;


-- =====================================================================
--  10. BACKFILL
--
--  If auth users already existed before this file was run, give them the
--  profile row the trigger would have made.
-- =====================================================================
insert into public.profiles (id, username, full_name, role)
select
  u.id,
  lower(regexp_replace(split_part(u.email, '@', 1), '[^a-zA-Z0-9_]', '', 'g')) || left(replace(u.id::text, '-', ''), 4),
  coalesce(nullif(u.raw_user_meta_data ->> 'full_name', ''), initcap(split_part(u.email, '@', 1))),
  coalesce(nullif(u.raw_user_meta_data ->> 'role', ''), 'worker')
from auth.users u
where not exists (select 1 from public.profiles p where p.id = u.id)
  and u.email is not null
on conflict (id) do nothing;


-- =====================================================================
--  Done. Verify with:
--
--    select table_name from information_schema.tables
--     where table_schema = 'public' order by 1;
--    -- expect: connections, offers, posts, profiles
--
--    select tablename, rowsecurity from pg_tables
--     where schemaname = 'public' order by 1;
--    -- expect: rowsecurity = true on all four
-- =====================================================================
